[2018-03-10 05:31:46] request.INFO: Matched route "cotizacion_mail". {"route_parameters":{"_controller":"AppBundle\\Controller\\CotizacionController::mailAction","id":"81","_route":"cotizacion_mail"},"request_uri":"http://139.59.157.165/pospublicarte/web/cotizacion/mail/81"} []
[2018-03-10 05:31:46] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-10 05:31:46] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-10 05:31:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-10 05:32:16] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host mail.damtec.mx [Connection timed out #110] [] []
[2018-03-13 01:34:26] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::newAction","_route":"cliente_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/new"} []
[2018-03-13 01:34:26] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-13 01:34:26] security.DEBUG: User was reloaded from a user provider. {"username":"venta2","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-13 01:34:26] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS", "89670", "ALDAMA", "EJ. LA COLMENA", "KM. 35", null, "ALDAMA", 1, 27]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS\", \"89670\", \"ALDAMA\", \"EJ. LA COLMENA\", \"KM. 35\", null, \"ALDAMA\", 1, 27]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-03-13 01:34:26] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-13 01:39:02] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::newAction","_route":"cliente_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/new"} []
[2018-03-13 01:39:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-13 01:39:02] security.DEBUG: User was reloaded from a user provider. {"username":"venta2","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-13 01:39:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS", "89670", "ALDAMA", "EJ. LA COLMENA", "KM. 35", "KM. 35", "ALDAMA", 1, 27]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS\", \"89670\", \"ALDAMA\", \"EJ. LA COLMENA\", \"KM. 35\", \"KM. 35\", \"ALDAMA\", 1, 27]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-03-13 01:39:02] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-13 01:43:47] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::newAction","_route":"cliente_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/new"} []
[2018-03-13 01:43:47] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-13 01:43:47] security.DEBUG: User was reloaded from a user provider. {"username":"venta2","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-13 01:43:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS", "89670", "ALDAMA", "LA COLMENA", "KM. 35", "KM. 35", "ALDAMA", 1, 27]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS\", \"89670\", \"ALDAMA\", \"LA COLMENA\", \"KM. 35\", \"KM. 35\", \"ALDAMA\", 1, 27]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-03-13 01:43:47] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-13 01:50:42] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::newAction","_route":"cliente_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/new"} []
[2018-03-13 01:50:42] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-13 01:50:42] security.DEBUG: User was reloaded from a user provider. {"username":"venta2","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-13 01:50:42] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS", "89670", "ALDAMA", "EJ. LA COLMENA", "KM. 35", null, "ALDAMA", 1, 27]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS\", \"89670\", \"ALDAMA\", \"EJ. LA COLMENA\", \"KM. 35\", null, \"ALDAMA\", 1, 27]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-03-13 01:50:42] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-13 01:54:02] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::newAction","_route":"cliente_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/new"} []
[2018-03-13 01:54:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-13 01:54:02] security.DEBUG: User was reloaded from a user provider. {"username":"venta2","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-13 01:54:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS", "89670", "ALDAMA", "EJ. LA COLMENA", "S\/N", null, "ALDAMA", 1, 27]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO domicilio (calle, cp, municipio, colonia, numext, numint, localidad, id_tipo, id_estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"CARR. EST. MANUEL SOTO LA MARINA KM. 35 EJ. LA COLMENA JUNTO A LA UNION GANADERA REG. DE TAMPS. ALDAMA TAMAULIPAS\", \"89670\", \"ALDAMA\", \"EJ. LA COLMENA\", \"S\\/N\", null, \"ALDAMA\", 1, 27]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'calle' at row 1 at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-03-13 01:54:02] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-27 19:39:10] request.INFO: Matched route "cliente_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::indexAction","_route":"cliente_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/"} []
[2018-03-27 19:39:10] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-27 19:39:10] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-27 19:39:10] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-27 19:39:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-27 19:39:10] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-27 19:39:10] request.INFO: Matched route "cliente_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::indexAction","_route":"cliente_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/"} []
[2018-03-27 19:39:10] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-27 19:39:10] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-27 19:39:10] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-27 19:39:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-27 19:39:10] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-28 23:59:12] request.INFO: Matched route "cliente_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::indexAction","_route":"cliente_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/"} []
[2018-03-28 23:59:12] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-28 23:59:12] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-28 23:59:12] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-28 23:59:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-28 23:59:12] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-03-28 23:59:12] request.INFO: Matched route "cliente_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\ClienteController::indexAction","_route":"cliente_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/cliente/"} []
[2018-03-28 23:59:12] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-03-28 23:59:12] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-28 23:59:12] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-28 23:59:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-03-28 23:59:12] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-10 18:45:32] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-04-10 18:45:32] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-10 18:45:32] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-10 18:45:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 397 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:397)"} []
[2018-04-10 18:45:32] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-10 18:47:17] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-04-10 18:47:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-10 18:47:17] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-10 18:47:17] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 397 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:397)"} []
[2018-04-10 18:47:17] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-10 18:49:47] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-04-10 18:49:47] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-10 18:49:47] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-10 18:49:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 397 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:397)"} []
[2018-04-10 18:49:47] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-10 19:08:34] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-04-10 19:08:34] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-10 19:08:34] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-10 19:08:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 397 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:397)"} []
[2018-04-10 19:08:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-13 13:23:27] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-04-13 13:23:27] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-13 13:23:27] security.DEBUG: User was reloaded from a user provider. {"username":"cobrosadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-13 13:23:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 397 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 233 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:397)"} []
[2018-04-13 13:23:27] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
